version: '3'
services:
#t   reverse-proxy:
#t    image: traefik
#t    command: --api
#t    labels:
#t      - "traefik.frontend.rule=Host:traefik.domainname"
#t      - "traefik.port=8080"
#t    ports:
#t      - "80:80"
#t      - "443:443"
#t    networks:
#t      - home
#t    volumes:
#t      - /var/run/docker.sock:/var/run/docker.sock
#t      - ./traefik/traefik.toml:/traefik.toml
#t      - ./traefik/acme.json:/acme.json
#t    restart: always
#t    env_file: uidgid.env
#t    container_name: reverse-proxy

  speedtest:
    image: piersonjarvis/speedtest
#t    labels:
#t      - "traefik.frontend.rule=Host:speedtest.domainname"
#l    ports:
#l      - 80:80
    restart: always
    env_file: uidgid.env
    networks:
      - home
    container_name: speedtest

  portainer:
    image: portainer/portainer
#t    labels:
#t      - "traefik.frontend.rule=Host:portainer.domainname"
#l    ports:
#l      - 9000:9000
    restart: always
    networks:
      - home
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /configs/portainer:/data
    env_file: uidgid.env
    container_name: portainer

  watchtower:
    image: v2tec/watchtower
    restart: always
    env_file: uidgid.env
    networks:
      - home
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  netdata:
    image: titpetric/netdata
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - home
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    env_file: uidgid.env
    container_name: netdata
    hostname: netdata
#t    labels:
#t      - "traefik.frontend.rule=Host:netdata.domainname"
#l    ports:
#l      - 19999:19999

#1  plex:
#1    image: plexinc/pms-docker:plexpass
#1    restart: always
#1    networks:
#1      - home
#1    volumes:
#1      - /home/media:/data
#1      - ./configs/plex:/config
#1    env_file: uidgid.env
#1    container_name: plex
#1    hostname: plex
#1    environment:
#1      - ADVERTISE_IP=http://192.168.0.10:32400/
#1    ports:
#1      - 32400:32400/tcp
#1      - 3005:3005/tcp
#1      - 8324:8324/tcp
#1      - 32469:32469/tcp
#1      - 1900:1900/udp
#1      - 32410:32410/udp
#1      - 32412:32412/udp
#1      - 32413:32413/udp
#1      - 32414:32414/udp
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:plex.domainname"
#t#1      - "traefik.port=32400"

#1  sabnzbd:
#1    image: linuxserver/sabnzbd
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:sabnzbd.domainname"
#l#1    ports:
#l#1      - 8080:8080
#1    restart: always
#1    networks:
#1      - home
#1    volumes:
#1      - /home/media/Downloads/complete:/downloads
#1      - /home/media/Downloads/incomplete:/incomplete-downloads
#1      - ./configs/sabnzbd:/config
#1    env_file: uidgid.env
#1    container_name: sabnzbd
#1    hostname: sabnzbd

#1  sonarr:
#1    image: linuxserver/sonarr
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:sonarr.domainname"
#l#1    ports:
#l#1      - 8989:8989
#1    restart: always
#1    networks:
#1      - home
#1    volumes:
#1      - /home/media/Video/TVshows:/tv
#1      - /home/media/Downloads/complete:/downloads
#1      - ./configs/sonarr:/config
#1      - /etc/localtime:/etc/localtime:ro
#1    env_file: uidgid.env
#1    container_name: sonarr
#1    hostname: sonarr

#1  radarr:
#1    image: linuxserver/radarr
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:radarr.domainname"
#l#1    ports:
#l#1      - 7878:7878
#1    restart: always
#1    networks:
#1      - home
#1    volumes:
#1      - /home/media/Downloads/complete:/downloads
#1      - /home/media/Video/Movies:/movies
#1      - ./configs/radarr:/config
#1      - /etc/localtime:/etc/localtime:ro
#1    env_file: uidgid.env
#1    container_name: radarr
#1    hostname: radarr

#1  lidarr:
#1    image: linuxserver/lidarr
#1    restart: always
#1    env_file: uidgid.env
#1    networks:
#1      - home
#1    container_name: lidarr
#1    hostname: lidarr
#1    volumes:
#1      - /home/media/music:/music
#1      - ./configs/lidarr:/config
#1     - /home/media/Downloads/complete:/downloads
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:lidarr.domainname"
#l#1    ports:
#l#1      - 8686:8686

#1  plexstats:
#1    image: linuxserver/tautulli
#1    container_name: plexstats
#1    hostname: plexstats
#1    restart: always
#1    env_file: uidgid.env
#1    networks:
#1      - home
#1    volumes:
#1      - ./configs/tautulli:/config
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:plexstats.domainname"
#l#1    ports:
#l#1      - 8181:8181

#1  ombi:
#1    image: linuxserver/ombi
#1    restart: always
#1    env_file: uidgid.env
#1    container_name: ombi
#1    hostname: ombi
#1    networks:
#1     - home
#1    volumes:
#1      - ./configs/ombi:/config
#t#1    labels:
#t#1      - "traefik.frontend.rule=Host:requests.domainname"
#l#1    ports:
#l#1      - 3579:3579

#2  minecraft:
#2    image: linuxserver/mcmyadmin2
#t#2    labels:
#t#2      - "traefik.frontend.rule=Host:minecraft.domainname"
#t#2      - "traefik.port=8080"
#l#2    ports:
#l#2      - 8585:8080
#2    restart: always
#2    networks:
#2      - home
#2    volumes:
#2      - ./configs/minecraft:/minecraft
#2    ports:
#2      - "25565:25565"
#2    env_file: uidgid.env
#2    container_name: minecraft

#3  amp-server:
#3    image: piersonjarvis/cubecoders-amp-server
#3    restart: always
#3    container_name: amp
#3    volumes:
#3      - /home/minecraft:/home/AMP/.ampdata/.instances/Minecraft01
#3    ports:
#3      - 9081-9180:8081-8180
#3      - 25565:25565
#3      - 27015-27020:27015-27020
#3      - 2777-2778:2777-2778
#l#3      - 9080:8080
#t#3    labels:
#t#3      - "traefik.frontend.rule=Host:minecraft.domainname"
#t#3      - "traefik.port=8080"

#g  mumble:
#g    image: coppit/mumble-server
#g    networks:
#g      - home
#g    ports:
#g      - 64738:64738
#g    volumes:
#g      - ./configs/mumble:/data
#g    restart: always
#g    container_name: mumble
#t#g    labels:
#t#g      - "traefik.enable=false"

#4  steamcache:
#4    image: steamcache/generic
#4    restart: always
#4    networks: 
#4      - home
#4    container_name: steamcache
#4    volumes:
#4      - ./configs/steamcache:/data/cache
#4      - ./configs/steamcache-logs:/data/logs
#t#4    labels:
#t#4      - "traefik.frontend.rule=Host:steamcache.domainname"
#l#4    ports:
#l#4      80:80

#4  steamcache-dns:
#4    image: steamcache/steamcache-dns
#4    restart: always
#4    container_name: steamcache-dns
#4    networks:
#4      - home
#4    ports:
#4      - 53:53
#4    environment:
#4      - USE_GENERIC_CACHE=true
#4      - LANCACHE_IP=machineip

#5  heimdall:
#5    image: linuxserver/heimdall
#5    restart: always
#5    networks:
#5      - home
#5    container_name: heimdall
#5    env_file: uidgid.env
#5    volumes:
#5      - ./configs/heimdall:/config
#t#5    labels:
#t#5      - "traefik.frontend.rule=Host:homepage.domainname"
#t#5      - "traefik.port=80"
#l#5    ports:
#l#5      - 83:80

#5  organizr:
#5    image: lsiocommunity/organizr
#5    restart: always
#5    env_file: uidgid.env
#5    networks:
#5      - home
#5    container_name: organizr
#5    volumes:
#5      - ./configs/organizr:/config
#t#5    labels:
#t#5      - "traefik.frontend.rule=Host:movies.domainname"
#l#5    ports:
#l#5      - 82:80

#5  samba:
#5    image: piersonjarvis/webmin-samba
#5    restart: always
#5    networks:
#5      - home
#5    container_name: samba
#5    volumes:
#5     - "/home/media:/media/storage"
#5     - "~/Docker:/media/docker"
#5     - "./configs/samba:/data"
#5    ports:
#5     - 139:139
#5     - 445:445
#l#5     - 81:80
#5    hostname: samba
#t#5    labels:
#t#5      - "traefik.frontend.rule=Host:samba.domainname"

#6  nextcloud:
#6    image: nextcloud
#t#6    labels:
#t#6      - "traefik.frontend.rule=Host:nextcloud.domainname"
#t#6      - "traefik.backend=nextcloud"
#t#6      - "traefik.docker.network=home"
#t#6      - "traefik.port=80"
#l#6    ports:
#l#6      - 84:80
#6    volumes:
#6      - ./configs/nextcloud:/var/www/html
#6      - ./configs/nextcloud_data:/data
#6    restart: always
#6    networks:
#6      - home
#6    env_file: uidgid.env
#6    container_name: nextcloud

networks:
  home:
    external: true
